# Order Orchestration Service - Basic Configuration
spring:
  application:
    name: order-orchestration-service
  profiles:
    active: dev
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
    
  datasource:
    url: jdbc:postgresql://localhost:5432/eip_resso
    username: eip_resso_user
    password: eip_resso_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true

server:
  port: 8089
  servlet:
    context-path: /

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Apache Camel Configuration
camel:
  springboot:
    name: order-orchestration-service
    main-run-controller: true
    auto-startup: true
    duration-max-seconds: 0
    shutdown-timeout: 30

# Logging
logging:
  level:
    com.eipresso.orderorchestration: DEBUG
    org.apache.camel: INFO
    org.springframework: INFO 