# EIP-resso Phase 8 Clustering Demonstration
# Simplified setup to showcase clustering foundation

version: '3.8'

services:

  # =============================================================================
  # Core Infrastructure for Clustering Demo
  # =============================================================================

  # PostgreSQL (single instance for demo)
  postgres:
    image: postgres:14
    container_name: eip-resso-postgres-demo
    environment:
      POSTGRES_DB: eipresso
      POSTGRES_USER: eipresso
      POSTGRES_PASSWORD: eipresso123
      POSTGRES_MULTIPLE_DATABASES: config
    ports:
      - "5433:5432"
    volumes:
      - postgres-demo-data:/var/lib/postgresql/data
    networks:
      eip-resso-cluster:
        ipv4_address: 172.21.1.10

  # Redis for caching/session storage
  redis:
    image: redis:7-alpine
    container_name: eip-resso-redis-demo
    ports:
      - "6380:6379"
    volumes:
      - redis-demo-data:/data
    networks:
      eip-resso-cluster:
        ipv4_address: 172.21.1.20

  # Single Consul instance for service discovery
  consul:
    image: consul:1.15
    container_name: eip-resso-consul-demo
    command: agent -server -bootstrap-expect=1 -datacenter=eip-resso -node=consul-demo -bind=172.21.1.30 -client=0.0.0.0 -ui
    ports:
      - "8501:8500"
    networks:
      eip-resso-cluster:
        ipv4_address: 172.21.1.30

  # =============================================================================
  # Configuration Server - The Heart of Our Clustering Setup
  # =============================================================================

  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile.simple
    container_name: eip-resso-config-server
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/config
      - SPRING_DATASOURCE_USERNAME=eipresso
      - SPRING_DATASOURCE_PASSWORD=eipresso123
    ports:
      - "8889:8888"
    depends_on:
      - postgres
      - consul
    networks:
      eip-resso-cluster:
        ipv4_address: 172.21.2.100
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # =============================================================================
  # Hazelcast Management Center - Clustering Visualization
  # =============================================================================

  hazelcast-mancenter:
    image: hazelcast/management-center:5.3
    container_name: eip-resso-hazelcast-mc
    environment:
      - MC_DEFAULT_CLUSTER=eip-resso-cluster
      - MC_DEFAULT_CLUSTER_MEMBERS=config-server:5701
    ports:
      - "8081:8080"
    depends_on:
      - config-server
    networks:
      eip-resso-cluster:
        ipv4_address: 172.21.1.80

  # =============================================================================
  # Monitoring Stack
  # =============================================================================

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: eip-resso-prometheus-demo
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    ports:
      - "9091:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-demo-data:/prometheus
    networks:
      eip-resso-cluster:
        ipv4_address: 172.21.1.90

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: eip-resso-grafana-demo
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3001:3000"
    volumes:
      - grafana-demo-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      eip-resso-cluster:
        ipv4_address: 172.21.1.91

networks:
  eip-resso-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16

volumes:
  postgres-demo-data:
  redis-demo-data:
  prometheus-demo-data:
  grafana-demo-data: 