server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eip_resso
    username: eip_resso_user
    password: eip_resso_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  rabbitmq:
    host: localhost
    port: 5672
    username: eip_resso
    password: eip_resso_pass
    virtual-host: /
    connection-timeout: 30000
    requested-heartbeat: 60

  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        service-name: order-management-service
        instance-id: ${spring.application.name}:${server.port}
        health-check-path: /api/orders/health
        health-check-interval: 10s
        tags:
          - order-service
          - event-sourcing
          - active-passive-cluster

# Apache Camel Configuration
camel:
  springboot:
    name: OrderManagementCamelContext
    main-run-controller: true
    jmx-enabled: true
    endpoint-runtime-statistics-enabled: true
    load-statistics-enabled: true
    message-history: true
  component:
    rabbitmq:
      hostname: localhost
      port-number: 5672
      username: eip_resso
      password: eip_resso_pass
      automatic-recovery-enabled: true
      connection-timeout: 30000
      requested-heartbeat: 60

# Hazelcast Clustering Configuration
hazelcast:
  cluster-name: eip-resso-order-cluster
  network:
    port: 5703
    port-auto-increment: true
    join:
      multicast:
        enabled: false
      tcp-ip:
        enabled: true
        members:
          - 127.0.0.1:5703
          - 127.0.0.1:5704
  management-center:
    enabled: true
    url: http://localhost:8080/hazelcast-mancenter

# Logging Configuration
logging:
  level:
    com.eipresso.order: DEBUG
    org.apache.camel: INFO
    org.springframework.cloud.config: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] - %msg%n"

# Application-specific Configuration
order-management:
  event-sourcing:
    enabled: true
    batch-size: 100
  clustering:
    mode: active-passive
    leader-election: true
  monitoring:
    stale-order-check-interval: 300000 # 5 minutes
    stale-order-threshold-hours: 1
  integration:
    payment-service:
      timeout: 30000
    inventory-service:
      timeout: 15000
    notification-service:
      timeout: 10000 