# User Service Configuration for EIP-resso
# Managed by Config Server - supports environment-specific overrides

# Database Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eipresso_users
    username: eipresso_user
    password: eipresso_password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Jackson configuration
  jackson:
    default-property-inclusion: NON_NULL
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

# Management/Actuator Configuration - ENABLE REFRESH
management:
  endpoints:
    web:
      exposure:
        include: health,refresh,env,configprops,info,metrics
  endpoint:
    refresh:
      enabled: true
    health:
      show-details: always

# Apache Camel Configuration
camel:
  springboot:
    name: user-service-camel-context
    main-run-controller: true
    jmx-enabled: true
  component:
    servlet:
      mapping:
        context-path: /camel/*
  management:
    enabled: true
    level: All
  metrics:
    enabled: true

# JWT Configuration
eipresso:
  jwt:
    secret: eipresso-super-secret-key-for-jwt-tokens-must-be-256-bits-minimum-length-to-work-properly
    access-token-expiration: 900      # 15 minutes
    refresh-token-expiration: 604800  # 7 days
    issuer: eip-resso-user-service

# Hazelcast Clustering Configuration
hazelcast:
  cluster-name: eipresso-user-cluster
  network:
    port: 5701
    port-auto-increment: true
    join:
      multicast:
        enabled: false
      tcp-ip:
        enabled: true
        members:
          - 127.0.0.1:5701
          - 127.0.0.1:5702
          - 127.0.0.1:5703
  map:
    default:
      backup-count: 1
      time-to-live-seconds: 300
    idempotent-repository:
      backup-count: 1
      time-to-live-seconds: 3600  # 1 hour for duplicate prevention

# Security Configuration
security:
  password:
    encoder:
      strength: 12  # BCrypt strength

# Logging Configuration
logging:
  level:
    com.eipresso: DEBUG
    org.apache.camel: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'

# User Service Specific Configuration - TEST CONFIGURATION FOR REFRESH
user-service:
  security:
    max-failed-attempts: 5
    lockout-duration-minutes: 30
    password-reset-token-expiration-minutes: 15
  audit:
    cleanup-days: 90  # Keep audit events for 90 days
  profile-enrichment:
    enabled: true
    geolocation-service:
      url: http://ip-api.com/json/{ip}
      timeout: 5000
  # Test property for dynamic refresh testing
  test:
    message: "Config Server Updated - Version 3.0 - Centralized Config!"
    feature-enabled: true
    refresh-count: 3

# Service Discovery
spring.cloud.consul:
  discovery:
    service-name: user-service
    health-check-path: /actuator/health
    health-check-interval: 10s
    prefer-ip-address: true
    instance-id: user-service:${random.value} 