name: EIP-resso Phase 8 - Production Deployment

on:
  push:
    branches: [ main ]
    paths: 
      - 'config-server/**'
      - 'eip-resso-clustering/**'
  pull_request:
    branches: [ main ]

env:
  JAVA_VERSION: '17'
  REGISTRY: ghcr.io
  IMAGE_NAME: eip-resso

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        
    - name: Build with Maven
      run: mvn clean package -DskipTests -pl config-server,eip-resso-clustering
      
    - name: Run Unit Tests
      run: mvn test -pl config-server,eip-resso-clustering
      
    - name: Integration Tests with TestContainers
      run: mvn verify -pl config-server -Dspring.profiles.active=test
      
    - name: Generate Test Reports
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Maven Tests
        path: '**/surefire-reports/*.xml'
        reporter: java-junit

  security-scan:
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: OWASP Dependency Check
      run: |
        mvn org.owasp:dependency-check-maven:check
        
    - name: Upload Security Report
      uses: actions/upload-artifact@v3
      with:
        name: security-report
        path: target/dependency-check-report.html

  build-docker-images:
    runs-on: ubuntu-latest
    needs: [build-and-test, security-scan]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build Blue Image
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:blue-${{ github.sha }} \
          -f config-server/Dockerfile.simple config-server/
          
    - name: Build Green Image  
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:green-${{ github.sha }} \
          -f config-server/Dockerfile.simple config-server/

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build-docker-images
    environment: staging
    
    steps:
    - name: Deploy to Staging
      run: |
        echo "🚀 Deploying to staging environment..."
        # Deploy commands would go here
        
    - name: Run Smoke Tests
      run: |
        echo "🧪 Running smoke tests..."
        # Smoke test commands would go here

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment: production
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Blue-Green Deployment
      run: |
        echo "🔄 Executing Blue-Green deployment..."
        # Blue-Green deployment logic would go here
        
    - name: Health Check
      run: |
        echo "❤️ Performing production health checks..."
        # Health check commands would go here
        
    - name: Rollback on Failure
      if: failure()
      run: |
        echo "↩️ Rolling back deployment..."
        # Rollback logic would go here
